CREATE TABLE IF NOT EXISTS raw.devitjobs (
  cpc DECIMAL(5, 2),
  _id VARCHAR(24),
  jobUrl VARCHAR(255),
  isPartner BOOLEAN,
  isPaused BOOLEAN,
  longitude DECIMAL(11, 8),
  latitude DECIMAL(11, 8),
  cityCategory VARCHAR(50),
  stateCategory VARCHAR(50),
  logoImg VARCHAR(500),
  activeFrom TIMESTAMP,
  candidateContactWay VARCHAR(50),
  redirectJobUrl VARCHAR(500),
  remoteType VARCHAR(50),
  workplace VARCHAR(50),
  company VARCHAR(255),
  address VARCHAR(255),
  actualCity VARCHAR(50),
  postalCode VARCHAR(10),
  companyType VARCHAR(50),
  companySize VARCHAR(50),
  hasVisaSponsorship VARCHAR(50),
  language VARCHAR(50),
  perkKeys TEXT[],
  name VARCHAR(255),
  jobType VARCHAR(50),
  expLevel VARCHAR(50),
  annualSalaryFrom INT,
  annualSalaryTo INT,
  techCategory VARCHAR(50),
  technologies TEXT[],
  filterTags TEXT[],
  source VARCHAR(25),
  ingested_ts TIMESTAMP
);