INSERT INTO raw.devitjobs (
  cpc,
  _id,
  jobUrl,
  isPartner,
  isPaused,
  longitude,
  latitude,
  cityCategory,
  stateCategory,
  logoImg,
  activeFrom,
  candidateContactWay,
  redirectJobUrl,
  remoteType,
  workplace,
  company,
  address,
  actualCity,
  postalCode,
  companyType,
  companySize,
  hasVisaSponsorship,
  language,
  perkKeys,
  name,
  jobType,
  expLevel,
  annualSalaryFrom,
  annualSalaryTo,
  techCategory,
  technologies,
  filterTags,
  source,
  ingested_ts
) VALUES (
  %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,
  %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,
  %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, CURRENT_TIMESTAMP
);