INSERT INTO staging.jobs (
  job_id, source_system, job_url, job_title, company_name, company_logo, 
  job_industry, job_type, job_level, job_description, job_excerpt, is_partner,
  is_paused, location, latitude, longitude, city_category, state_category, address,
  postal_code, remote_type, workplace, candidate_contact_way, redirect_job_url,
  salary_min, salary_max, salary_currency, perk_keys, company_size, company_type,
  tech_category, tech_stack, filter_tags, has_visa_sponsorship,
  language_requirements, published_at, last_update, ingested_ts, staging_ts
)
SELECT 
  id::TEXT AS job_id,
  source AS source_system,
  url AS job_url,
  jobTitle AS job_title,
  companyName AS company_name,
  companyLogo AS company_logo,
  jobIndustry AS job_industry,
  jobType AS job_type,
  jobLevel AS job_level,
  jobDescription AS job_description,
  jobExcerpt AS job_excerpt,
  NULL AS is_partner,
  NULL AS is_paused,
  jobGeo AS location,
  NULL AS latitude,
  NULL AS longitude,
  NULL AS city_category,
  NULL AS state_category,
  NULL AS address,
  NULL AS postal_code,
  NULL AS remote_type,
  NULL AS workplace,
  NULL AS candidate_contact_way,
  jobSlug AS redirect_job_url,
  annualSalaryMin AS salary_min,
  annualSalaryMax AS salary_max,
  salaryCurrency AS salary_currency,
  NULL AS perk_keys,
  NULL AS company_size,
  NULL AS company_type,
  NULL AS tech_category,
  NULL AS tech_stack,
  NULL AS filter_tags,
  NULL AS has_visa_sponsorship,
  NULL AS language_requirements,
  pubDate AS published_at,
  lastUpdate AS last_update,
  ingested_ts AS ingested_ts,
  CURRENT_TIMESTAMP AS staging_ts
FROM raw.jobicy

UNION ALL

SELECT 
  _id AS job_id,
  source AS source_system,
  jobUrl AS job_url,
  name AS job_title,
  company AS company_name,
  logoImg AS company_logo,
  NULL AS job_industry,
  ARRAY[jobType] AS job_type,
  expLevel AS job_level,
  NULL AS job_description,
  NULL AS job_excerpt,
  isPartner AS is_partner,
  isPaused AS is_paused,
  actualCity AS location,
  latitude AS latitude,
  longitude AS longitude,
  cityCategory AS city_category,
  stateCategory AS state_category,
  address AS address,
  postalCode AS postal_code,
  remoteType AS remote_type,
  workplace AS workplace,
  candidateContactWay AS candidate_contact_way,
  redirectJobUrl AS redirect_job_url,
  annualSalaryFrom AS salary_min,
  annualSalaryTo AS salary_max,
  NULL AS salary_currency,
  perkKeys AS perk_keys,
  companySize AS company_size,
  companyType AS company_type,
  techCategory AS tech_category,
  technologies AS tech_stack,
  filterTags AS filter_tags,
  hasVisaSponsorship AS has_visa_sponsorship,
  ARRAY[language] AS language_requirements,
  activeFrom AS published_at,
  NULL AS last_update,
  ingested_ts AS ingested_ts,
  CURRENT_TIMESTAMP AS staging_ts
FROM raw.devitjobs;